#!/bin/sh
mkdir -p /tmp/mosdns
process_data() {
    awk '!/^#/ && NF {
        name=$2; ip=$1;
        if (NF >= 4) { name=$4; ip=$3; }
        split(ip, arr, ".");
        ptr_name = arr[4]"."arr[3]"."arr[2]"."arr[1]".in-addr.arpa.";
        print name". 60 IN A "ip;
        print name".lan. 60 IN A "ip;
        print ptr_name" 60 IN PTR "name".lan.";
    }' 2>/dev/null
}
[ -d "/tmp/hosts" ] && cat /tmp/hosts/* 2>/dev/null | process_data > /tmp/mosdns/mosdns_hosts.txt
[ -f "/tmp/dhcp.leases" ] && cat /tmp/dhcp.leases | process_data >> /tmp/mosdns/mosdns_hosts.txt
